version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APPS_SCRIPT_URL=${APPS_SCRIPT_URL}
  whatsapp-bot:
    build: ./whatsapp-bot
    depends_on:
      - backend
    volumes:
      - ./whatsapp-bot:/app 